name: Script Checks

permissions:
  contents: read

on:
  push:
    paths:
      - "**/*.sh"
  pull_request:
    paths:
      - "**/*.sh"
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reviewdog_flags: "-fail-level=error"

  shfmt:
    name: Shell Fomatting
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
